batch_size: 256
fraction_training_data: 60
hidden_layers: 1
hidden_nodes: 64
momentum: 0.8
learning_rate: 0.6

inputs:
  - "/XFEL.DIAG/BPM/BPME.2806.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2818.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2830.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2940.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2849.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2861.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2873.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2885.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2897.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2916.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2922.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2928.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2934.SA3/X.TD"
  - "/XFEL.DIAG/BPM/BPME.2806.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2818.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2830.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2940.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2849.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2861.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2873.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2885.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2897.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2916.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2922.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2928.SA3/Y.TD"
  - "/XFEL.DIAG/BPM/BPME.2934.SA3/Y.TD"
  - "/XFEL.FEL/XGM/XGM.3130.T10/INTENSITY.SA3.TD"
  - "/XFEL.DIAG/BEAM_ENERGY_MEASUREMENT/T4/ENERGY.SA3/Value"
  - "/XFEL.SDIAG/BCM.DAQ/BCM.416.B2.1/COMPRESSION.TD"
  - "/XFEL.SDIAG/BCM.DAQ/BCM.416.B2.2/COMPRESSION.TD"
  - "/XFEL.UTIL/HIGH_LEVEL_STATUS/PHOTON_ENERGY.SA3/PHOTON_ENERGY_INPUT_1/Value"
  
outputs:
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/COM_X_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/COM_Y_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/BEAMSIZE_X_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/BEAMSIZE_Y_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/KURTOSIS_X_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/KURTOSIS_Y_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/SKEWNESS_X_MEASUREMENT'
  - 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA3/SKEWNESS_Y_MEASUREMENT'
