batch_size: 64
fraction_training_data: 60
hidden_layers: 2
hidden_nodes: 128
momentum: 0.8
inputs:
- XFEL.DIAG/BPM/BPME.2337.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2264.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2343.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2288.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2313.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2276.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2300.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2331.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2349.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2325.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2380.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2355.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2319.SA2/X.SA2
- XFEL.DIAG/BPM/BPME.2337.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2264.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2343.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2288.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2313.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2276.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2300.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2331.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2349.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2325.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2380.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2355.SA2/Y.SA2
- XFEL.DIAG/BPM/BPME.2319.SA2/Y.SA2
- XFEL.FEL/XGM/XGM.2595.T6/INTENSITY.TD
- XFEL.FEL/XGM.POSMON/XGM.2595.T6/IX.POS
- XFEL.FEL/XGM.POSMON/XGM.2595.T6/IY.POS
- XFEL.UTIL/HIGH_LEVEL_STATUS/PHOTON_ENERGY.SA2/PHOTON_ENERGY_INPUT_1
- XFEL.DIAG/BEAM_ENERGY_MEASUREMENT/T3/ENERGY.SA2
- XFEL.DIAG/BEAM_ENERGY_MEASUREMENT/T5/ENERGY.SA2
learning_rate: 0.1
outputs:
- 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA2/COM_X_MEASUREMENT'
- 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA2/COM_Y_MEASUREMENT'
- 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA2/BEAMSIZE_X_MEASUREMENT'
- 'XFEL.UTIL/DYNPROP/BEAM_PREDICT.SA2/BEAMSIZE_Y_MEASUREMENT'
